In [1]:
import numpy as np

In [2]:
rs = np.random.RandomState(321) # create a random state object
arr = rs.rand(5,5) # create a 5x5 array of random numbers
print(arr)

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]


### element-wise addition, subtraction, multiplication and division

In [3]:
print(arr + 10)
print(arr - 10)
print(arr * 10)
print(arr / 10)

[[10.88594794 10.07791236 10.97964616 10.24767146 10.75288472]
 [10.52667564 10.90755375 10.8840703  10.08926896 10.5173446 ]
 [10.34362129 10.21229369 10.36067344 10.27077517 10.76162502]
 [10.4780419  10.09899468 10.27539478 10.79442731 10.51397031]
 [10.45329481 10.25515125 10.1139766  10.82431305 10.3177535 ]]
[[-9.11405206 -9.92208764 -9.02035384 -9.75232854 -9.24711528]
 [-9.47332436 -9.09244625 -9.1159297  -9.91073104 -9.4826554 ]
 [-9.65637871 -9.78770631 -9.63932656 -9.72922483 -9.23837498]
 [-9.5219581  -9.90100532 -9.72460522 -9.20557269 -9.48602969]
 [-9.54670519 -9.74484875 -9.8860234  -9.17568695 -9.6822465 ]]
[[8.85947941 0.77912359 9.79646157 2.47671458 7.52884718]
 [5.26675636 9.07553753 8.84070297 0.8926896  5.17344596]
 [3.43621292 2.12293694 3.60673442 2.70775173 7.61625018]
 [4.78041899 0.98994677 2.75394778 7.94427309 5.13970314]
 [4.53294809 2.55151249 1.13976602 8.24313051 3.17753499]]
[[0.08859479 0.00779124 0.09796462 0.02476715 0.07528847]
 [0.05266756 0.0907

In [4]:
# the above operations can be performed using numpy built-in functions
# which can save memory as the output can be stored in the original array rather than assigning new memory
arr1 = np.array([1,2,3])
np.add(arr1, [8,9,10], out=arr1) # perform addition and store the result in arr1
print('adding 8,9,10 to arr1:', arr1)

np.subtract(arr1, [8,9,10], out=arr1) # perform subtraction and store the result in arr1
print('subtracting 8,9,10 from arr1:', arr1)

np.multiply(arr1, [1,2,3], out=arr1) # perform multiplication and store the result in arr1
print('multiplying arr1 by [1,2,3]:', arr1)

adding 8,9,10 to arr1: [ 9 11 13]
subtracting 8,9,10 from arr1: [1 2 3]
multiplying arr1 by [1,2,3]: [1 4 9]


### element-wise exponentiation

In [5]:
print(np.exp(arr))

[[2.42528233 1.08102791 2.66351361 1.28103899 2.12311578]
 [1.69329382 2.47825269 2.42073278 1.09337469 1.67756711]
 [1.41004454 1.23651099 1.434295   1.31098029 2.14175378]
 [1.61291306 1.10406042 1.31705052 2.21317317 1.67191607]
 [1.573488   1.29065682 1.1207259  2.28031377 1.37403752]]


### element-wise logorithm

In [6]:
# natural log
print(np.log(arr))      

[[-0.12109709 -2.55217069 -0.02056384 -1.39565218 -0.28384316]
 [-0.64117041 -0.09700248 -0.1232187  -2.41610145 -0.6590461 ]
 [-1.06821512 -1.54978461 -1.01978232 -1.30646642 -0.27230095]
 [-0.73805689 -2.3126892  -1.28954965 -0.23013379 -0.66558977]
 [-0.79121257 -1.36589877 -2.1717621  -0.19320491 -1.14647936]]


In [7]:
# base 2
print(np.log2(arr))     

[[-0.17470617 -3.682004   -0.02966734 -2.01350047 -0.40949912]
 [-0.92501337 -0.139945   -0.177767   -3.48569757 -0.95080253]
 [-1.54110866 -2.23586657 -1.4712349  -1.88483263 -0.39284723]
 [-1.06479102 -3.33650524 -1.86042689 -0.33201288 -0.96024306]
 [-1.14147846 -1.97057539 -3.13319041 -0.27873576 -1.65402009]]


In [8]:
# base 10
print(np.log10(arr))    

[[-0.0525918  -1.10839365 -0.00893076 -0.60612404 -0.12327152]
 [-0.27845677 -0.04212764 -0.0535132  -1.04929953 -0.28622008]
 [-0.46391993 -0.67306291 -0.44288584 -0.56739116 -0.1182588 ]
 [-0.32053404 -1.00438816 -0.5600443  -0.09994584 -0.28906196]
 [-0.34361925 -0.5932023  -0.9431843  -0.08390782 -0.49790966]]


### element-wise square root

In [9]:
print(np.sqrt(arr))

[[0.94124808 0.27912785 0.98977076 0.49766601 0.8676893 ]
 [0.72572422 0.95265616 0.94025012 0.29877912 0.71926671]
 [0.5861922  0.4607534  0.60056094 0.52036062 0.8727113 ]
 [0.69140574 0.3146342  0.5247807  0.89130652 0.71691723]
 [0.67327172 0.50512498 0.33760421 0.90791687 0.56369628]]


### element-wise sine and cosine

In [10]:
print(np.sin(arr))

[[0.77451496 0.07783356 0.83030022 0.24514714 0.68374664]
 [0.50266227 0.78800001 0.77332588 0.08915044 0.49457398]
 [0.33689889 0.21070265 0.35290443 0.26747845 0.69009841]
 [0.46004147 0.09883307 0.27192686 0.71346244 0.49163846]
 [0.43792997 0.25239176 0.11372999 0.73408147 0.31243331]]


In [11]:
print(np.cos(arr))

[[0.63255559 0.99696637 0.55731638 0.96948588 0.72971949]
 [0.86448288 0.61567523 0.63400874 0.99601817 0.86913554]
 [0.94154083 0.9775502  0.93565938 0.96356384 0.72371554]
 [0.88789743 0.99510403 0.96231792 0.70069347 0.87079942]
 [0.89900909 0.96762513 0.9935117  0.6790614  0.9499397 ]]


### sum along a specified axis

| Axis | Dimension | Direction | Name |
| :--- | :--- | :--- | :--- |
| **Axis 0** | The first dimension | **Vertical** | **Rows** | 
| **Axis 1** | The second dimension | **Horizontal** | **Columns** | 

In [18]:
print(arr)
print(' ')
# sum of each column/vertical sum
print('sum of each column:', np.sum(arr, axis=0))   
print(' ')
# sum along the row/horizontal sum
print('sum along the row:', np.sum(arr, axis=1))    

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]
 
sum of each column: [2.68758158 1.55190573 2.61376128 2.22645595 2.86357814]
 
sum along the row: [2.94406263 2.92491324 1.94898862 2.16082898 1.96448921]


### Compute the min and max along a specified axis

In [22]:
print(arr)
print(' ')

# calculate along each column/vertical 
print('Column min:', np.min(arr, axis=0))# calculate min along each column/vertical min
print('Column max:', np.max(arr, axis=0)) # calculate max along each column/vertical max
print(' ')

# calculate along the row/horizontal 
print('Row min:', np.min(arr, axis=1)) # calculate min along the row/horizontal
print('Row max:', np.max(arr, axis=1))  # calculate max along the row/horizontal
print(' ')
# if axis not specified, calculate the max/min value of all elements
print('Array max:', np.max(arr))
print('Array min:', np.min(arr))

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]
 
Column min: [0.34362129 0.07791236 0.1139766  0.08926896 0.3177535 ]
Column max: [0.88594794 0.90755375 0.97964616 0.82431305 0.76162502]
 
Row min: [0.07791236 0.08926896 0.21229369 0.09899468 0.1139766 ]
Row max: [0.97964616 0.90755375 0.76162502 0.79442731 0.82431305]
 
Array max: 0.9796461573123091
Array min: 0.07791235871612434


### Compute the indices of the min and max along a specified axis

In [26]:
print(arr)
print(' ')

# along the column - index of min and max
print('Column indices of min and max values:')
print(np.argmin(arr, axis=0))
print(np.argmax(arr, axis=0))
print(' ')
# along the row - index of min and max
print('Row indices of min and max values:')
print(np.argmin(arr, axis=1))
print(np.argmax(arr, axis=1))
print(' ')
# if axis not specified, return the index of the flattened array
print('Index of min value in flattened array:', np.argmin(arr))
print('Index of max value in flattened array:', np.argmax(arr))

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]
 
Column indices of min and max values:
[2 0 4 1 4]
[0 1 0 4 2]
 
Row indices of min and max values:
[1 3 1 1 2]
[2 1 4 3 3]
 
Index of min value in flattened array: 1
Index of max value in flattened array: 2


### Compute the key statistics

Mean, Median, Standard Deviation, Variance

In [36]:

print(arr)
print(' ')
print('Array mean:', np.mean(arr))# compute the overall mean
print('Mean along column:', np.mean(arr, axis=0))   # compute the mean along the column
print('Mean along row:', np.mean(arr, axis=1))  # compute the mean along the row
print(' ')
print('Array median:', np.median(arr))# compute the overall median
print('Median along column:', np.median(arr, axis=0))  # compute the median along the column
print('Median along row:', np.median(arr, axis=1))   # compute the median along the row
print(' ')
print('Array standard deviation:', np.std(arr)) # compute the overall standard deviation
print('Standard deviation along column:', np.std(arr, axis=0))  # compute the standard deviation along the column
print('Standard deviation along row:', np.std(arr, axis=1))   # compute the standard deviation along the row
print(' ')
print('Array variance:', np.var(arr)) # compute the overall variance
print('Variance along column:', np.var(arr, axis=0))  # compute the variance along the column
print('Variance along row:', np.var(arr, axis=1))   # compute the variance along the row
# compute 5, 65, and 95 percentiles of the array
print('5, 65, and 95 percentiles:', np.percentile(arr, [5, 65, 95]))


[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]
 
Array mean: 0.4777313072940956
Mean along column: [0.53751632 0.31038115 0.52275226 0.44529119 0.57271563]
Mean along row: [0.58881253 0.58498265 0.38979772 0.4321658  0.39289784]
 
Array median: 0.45329480890139495
Median along column: [0.4780419  0.21229369 0.36067344 0.27077517 0.5173446 ]
Median along row: [0.75288472 0.52667564 0.34362129 0.4780419  0.3177535 ]
 
Array standard deviation: 0.2864618030130311
Standard deviation along column: [0.1842541  0.30594529 0.34463185 0.30391276 0.16713486]
Standard deviation along row: [0.35926488 0.29906929 0.19334429 0.23478081 0.24173735]
 
Array variance: 0.08206036458547664
Variance along column: [0.03394957 0.09360252 0.11877111 0.09236297 0.027934

### Compute the covariance & correlation

In [37]:
print(np.cov(arr))

[[ 0.16133907  0.02319439  0.04179836  0.00310419 -0.04504838]
 [ 0.02319439  0.11180305 -0.00735614 -0.08553641 -0.08503809]
 [ 0.04179836 -0.00735614  0.04672752  0.01222163 -0.01237595]
 [ 0.00310419 -0.08553641  0.01222163  0.06890254  0.06063218]
 [-0.04504838 -0.08503809 -0.01237595  0.06063218  0.07304618]]


In [38]:
print(np.corrcoef(arr[:,0], arr[:,1]))

[[ 1.         -0.18176127]
 [-0.18176127  1.        ]]


### compute cumulative sum & product

In [43]:
print(arr)
print(' ')
# calculate the cumulative sums along the column/vertical
print(np.cumsum(arr, axis=0))    

print(' ')
# sum of each column/vertical sum
print('sum of each column:', np.sum(arr, axis=0))   


[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]
 
[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [1.41262358 0.98546611 1.86371645 0.33694042 1.27022931]
 [1.75624487 1.19775981 2.2243899  0.60771559 2.03185433]
 [2.23428677 1.29675448 2.49978467 1.4021429  2.54582465]
 [2.68758158 1.55190573 2.61376128 2.22645595 2.86357814]]
 
sum of each column: [2.68758158 1.55190573 2.61376128 2.22645595 2.86357814]


In [44]:
print(arr)
print(' ')  
# calculate the cumulative sums along the row/horizontal
print(np.cumsum(arr, axis=1))    

print(' ')
# sum along the row/horizontal sum
print('sum along the row:', np.sum(arr, axis=1))    

[[0.88594794 0.07791236 0.97964616 0.24767146 0.75288472]
 [0.52667564 0.90755375 0.8840703  0.08926896 0.5173446 ]
 [0.34362129 0.21229369 0.36067344 0.27077517 0.76162502]
 [0.4780419  0.09899468 0.27539478 0.79442731 0.51397031]
 [0.45329481 0.25515125 0.1139766  0.82431305 0.3177535 ]]
 
[[0.88594794 0.9638603  1.94350646 2.19117792 2.94406263]
 [0.52667564 1.43422939 2.31829969 2.40756865 2.92491324]
 [0.34362129 0.55591499 0.91658843 1.1873636  1.94898862]
 [0.4780419  0.57703658 0.85243135 1.64685866 2.16082898]
 [0.45329481 0.70844606 0.82242266 1.64673571 1.96448921]]
 
sum along the row: [2.94406263 2.92491324 1.94898862 2.16082898 1.96448921]


### Element-wise comparison

In [45]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([5,4,3,2,1])

In [46]:
# return an array of bools
print(arr1 == arr2)    
print(arr1 < 3)

[False False  True False False]
[ True  True False False False]


### Compute element-wise min and max of two arrays

In [47]:
arr1 = np.array([1, 3, 5, 7, 9])
arr2 = np.array([0, 4, 3, 8, 7])
print(np.maximum(arr1, arr2))
print(np.minimum(arr1, arr2))

[1 4 5 8 9]
[0 3 3 7 7]


### Split fractional and integral parts of a floating-point array

In [48]:
rs = np.random.RandomState(321) # create a random state object
arr1 = rs.rand(10) * 10
re, intg = np.modf(arr1)
print('fractional: ', re)
print('integral: ', intg)

fractional:  [0.85947941 0.77912359 0.79646157 0.47671458 0.52884718 0.26675636
 0.07553753 0.84070297 0.8926896  0.17344596]
integral:  [8. 0. 9. 2. 7. 5. 9. 8. 0. 5.]
